# Generated by Django 5.0.14 on 2025-12-12 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("clinics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="clinic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="clinics.clinic",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddField(
            model_name="otprequest",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="otp_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["role", "clinic"], name="accounts_us_role_6c7ab7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["username", "email"], name="accounts_us_usernam_b095cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="otprequest",
            index=models.Index(
                fields=["phone_number", "created_at"],
                name="accounts_ot_phone_n_6e04f3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="otprequest",
            index=models.Index(
                fields=["user", "is_verified"], name="accounts_ot_user_id_b8b85c_idx"
            ),
        ),
    ]
