# Generated by Django 5.0.14 on 2025-12-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="otprequest",
            name="code",
        ),
        migrations.AddField(
            model_name="otprequest",
            name="attempt_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="otprequest",
            name="code_hash",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="otprequest",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="otprequest",
            name="purpose",
            field=models.CharField(
                choices=[("LOGIN", "Login"), ("RECOVERY", "Recovery")],
                db_index=True,
                default="LOGIN",
                max_length=16,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="otprequest",
            name="sent_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name="otprequest",
            index=models.Index(
                fields=["phone_number", "purpose", "created_at"],
                name="accounts_ot_phone_n_745a49_idx",
            ),
        ),
    ]
