# Generated by Django 5.0.14 on 2025-12-12 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_seed_default_plans"),
        ("clinics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("invoice_id", models.CharField(blank=True, max_length=128)),
                ("reference_id", models.CharField(max_length=128, unique=True)),
                ("checkout_url", models.URLField(blank=True)),
                ("transaction_id", models.CharField(blank=True, max_length=128)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_payments",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="billing_payments",
                        to="billing.plan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="billing_bil_status_14412f_idx",
                    ),
                    models.Index(
                        fields=["clinic", "status"],
                        name="billing_bil_clinic__3cce7f_idx",
                    ),
                    models.Index(
                        fields=["reference_id"], name="billing_pay_ref_id_idx"
                    ),
                ],
            },
        ),
    ]
